version: "3"
services:
  app:
    build:
      args:
        user: jonas
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: posty
    container_name: posty-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - posty

  db:
    image: postgres:9.6
    container_name: posty-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    volumes:
      - dados:/var/lib/postgresql/data
    networks:
      - posty

  nginx:
    image: nginx:alpine
    container_name: posty-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - posty

volumes:
  dados:
networks:
  posty:
    driver: bridge
